config/routes.rb
OnlineStore::Application.routes.draw do
  get "home/index"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :comments
  match 'comment/destroy/:id/:article_id' => 'comments#destroy', :as => :delete_comment

  resources :categories
  resources :sessions
  resources :users
  resources :products
  resources :articles

  root :to => "home#index"
  
  match ':controller(/:action(/:id))(.:format)'

  namespace :admin do
    resources :categories
    match 'category/create' => 'categories#create', :as => :create_category
    match 'category/edit/:id' => 'categories#edit', :as => :edit_category
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.order('id DESC').limit(6).all
    @articles = Article.order('id DESC').limit(3).all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_articles.html.erb
<div class="hr_two"></div>
<h4>Listing Articles</h4>
<div class="hr_two"></div>
<section>
  <% articles.each do |article| %>
    <article class="articles">
      Title : <%= article.title %><br />
      Body : <%= truncate(article.body, :length => 60, :omission => '... (continued)') %>
      <ul>
        <li><%= link_to "See detail", article, :class => "no-border" %></li>
        <% unless session[:user_id].nil? %>
          <% if current_user.id.eql?(article.user_id) %>
            <li><%= link_to "Edit", edit_article_path(article) %></li>
            <li><%= link_to "Delete", article, :confirm => "Are you sure?", :method => :delete %></li>
          <% end %>
        <% end %>
      </ul>
    </article>
  <% end %>
</section>

app/views/home/_products.html.erb
<div class="hr_two"></div>
<h4>Listing Products</h4>
<div class="hr_two"></div>
<div class="products">
  <% products.each do |product| %>
    <div class="product">
      <p>
        Name : <%= product.name %><br />
        Price : <%= product.price %>
        <ul>
          <li><%= link_to "See more", product, :class => "see-more" %></li>
          <% unless session[:user_id].nil? %>
            <% if current_user.id.eql?(product.user_id) %>
              <li><%= link_to "Edit", edit_product_path(product), :class => "manage" %></li>
              <li><%= link_to "Delete", product, :method => :delete, :confirm => "Are You Sure?", :class => "manage" %></li>
            <% end %>
          <% end %>
        </ul>
      </p>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="content">
  <%= render :partial => "products", :locals => { :products => @products }  %>
  <br />
  <%= render :partial => "articles", :locals => { :articles => @articles }  %>
</div>