config/routes.rb
OnlineStore::Application.routes.draw do
  get "home/index"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :comments
  match 'comment/destroy/:id/:article_id' => 'comments#destroy', :as => :delete_comment

  resources :categories
  resources :sessions
  resources :users
  resources :products
  resources :articles

  root :to => "home#index"
  
  match ':controller(/:action(/:id))(.:format)'

  namespace :admin do
    resources :categories
    match 'category/create' => 'categories#create', :as => :create_category
    match 'category/edit/:id' => 'categories#edit', :as => :edit_category
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id

  validates :name, :presence => true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_filter :require_admin
  before_filter :find_category, :only => [:show, :edit, :update, :destroy]
  before_filter :parent_category, :only => [:new, :create, :edit]
  
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      flash.now[:notice] = "Category has been created"
      redirect_to admin_categories_path
    else
      flash.now[:error] = "Category failed to create"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update_attributes(params[:category])
      flash[:notice] = "Category has been updated"
      redirect_to admin_categories_path
    else
      flash[:error] = "Category failed to update"
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:notice] = "Category has been deleted"
      redirect_to admin_categories_path
    else
      flash[:error] = "Category has failed to delete"
      redirect_to admin_categories_path
    end
  end

  private
  def find_category
    @category = Category.find_by_id(params[:id])
    if @category.nil?
      flash[:error] = "Category was not found"
      redirect_to admin_categories_path
    end
  end

  def parent_category
    @parent_category = Category.where(["parent_id IS NULL"]).map{|x| [x.name, x.id]}
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :require_login, :only => [:show]
  before_filter :find_category, :only => [:show]

  def show
    @category = Category.find_by_id(params[:id])
    unless @category.parent_id.nil?
      @products = Product.where("category_id = ?", params[:id])
    else
      categories = Category.where("parent_id = ?", @category.id)
      child_categories = []
      categories.each do |category|
        child_categories << category.id
      end
      @products = Product.where("category_id = ?", params[:id])
      child_categories.each do |child_category|
        child_products = Product.where("category_id = ?", child_category)
        @products = @products + child_products
      end
    end
  end

  private
    def find_category
      @category = Category.find_by_id(params[:id])
      if @category.nil?
        flash[:notice] = "Category was not found"
        redirect_to root_url
      end
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="content">
  <%= form_for @category, :url => admin_category_path do |f| %>
    <% if @category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
        <ul>
          <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h3>New Category</h3>
    <table>
      <tbody>
          <tr>
            <td><%= f.label :name %></td>
            <td>:</td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td>Parent Category</td>
            <td>:</td>
            <td><%= f.select :parent_id, @parent_category, { :include_blank => true } %></td>
          </tr>
      </tbody>
    </table>
    <%= f.submit "Update", :class => "button" %><br /><br />
    <%= link_to "Back", admin_categories_path %>
  <% end %>
</div>

app/views/admin/categories/index.html.erb
<div class="content">
  <div class="hr_two"></div>
  <h4>Listing Categories</h4>
  <div class="hr_two"></div>
  <br />
  <%= link_to "New Category", new_admin_category_path %>
  <br />
  <table class="admin-categories">
    <thead>
      <tr>
        <th align="left">Name</th>
        <th align="left">Parent Category</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td align="left"><%= category.name %></td>
          <td align="left"><%= parent_category(category.parent_id) %></td>
          <td>
            <%= link_to "Show", admin_category_path(category.id) %>
            <%= link_to "Edit", admin_edit_category_path(category.id) %>
            <%= link_to "Destroy", admin_category_path(category.id), :confirm => "Are You Sure? ", :method => :delete, :class => "no-border" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/categories/new.html.erb
<div class="content">
  <%= form_for @category, :url => admin_create_category_path do |f| %>
    <% if @category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
        <ul>
          <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h3>New Category</h3>
    <table>
      <tbody>
          <tr>
            <td><%= f.label :name %></td>
            <td>:</td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td>Parent Category</td>
            <td>:</td>
            <td><%= f.select :parent_id, @parent_category, { :include_blank => '-Please Choose-' } %></td>
          </tr>
      </tbody>
    </table>
    <%= f.submit "Create", :class => "button" %>
    <%= link_to "Back", admin_categories_path %>
  <% end %>
</div>

app/views/admin/categories/show.html.erb
<div class="content">
  <h3>Show Category</h3>
  <p><strong>Name</strong> : <%= @category.name %></p>
  <p><strong>Parent Category</strong> : <%= !@category.parent_id.nil? ? parent_category(@category.parent_id) : "-" %></p>
  <%= link_to "Edit", admin_edit_category_path(@category.id) %>
  <%= link_to "Back", admin_categories_path %>
</div>