config/routes.rb
OnlineStore::Application.routes.draw do
  get "home/index"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :comments
  match 'comment/destroy/:id/:article_id' => 'comments#destroy', :as => :delete_comment

  resources :categories
  resources :sessions
  resources :users
  resources :products
  resources :articles

  root :to => "home#index"
  
  match ':controller(/:action(/:id))(.:format)'

  namespace :admin do
    resources :categories
    match 'category/create' => 'categories#create', :as => :create_category
    match 'category/edit/:id' => 'categories#edit', :as => :edit_category
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id

  validates :name, :presence => true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_filter :require_admin
  before_filter :find_category, :only => [:show, :edit, :update, :destroy]
  before_filter :parent_category, :only => [:new, :create, :edit]
  
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      flash.now[:notice] = "Category has been created"
      redirect_to admin_categories_path
    else
      flash.now[:error] = "Category failed to create"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update_attributes(params[:category])
      flash[:notice] = "Category has been updated"
      redirect_to admin_categories_path
    else
      flash[:error] = "Category failed to update"
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:notice] = "Category has been deleted"
      redirect_to admin_categories_path
    else
      flash[:error] = "Category has failed to delete"
      redirect_to admin_categories_path
    end
  end

  private
  def find_category
    @category = Category.find_by_id(params[:id])
    if @category.nil?
      flash[:error] = "Category was not found"
      redirect_to admin_categories_path
    end
  end

  def parent_category
    @parent_category = Category.where(["parent_id IS NULL"]).map{|x| [x.name, x.id]}
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :require_login, :only => [:show]
  before_filter :find_category, :only => [:show]

  def show
    @category = Category.find_by_id(params[:id])
    unless @category.parent_id.nil?
      @products = Product.where("category_id = ?", params[:id])
    else
      categories = Category.where("parent_id = ?", @category.id)
      child_categories = []
      categories.each do |category|
        child_categories << category.id
      end
      @products = Product.where("category_id = ?", params[:id])
      child_categories.each do |child_category|
        child_products = Product.where("category_id = ?", child_category)
        @products = @products + child_products
      end
    end
  end

  private
    def find_category
      @category = Category.find_by_id(params[:id])
      if @category.nil?
        flash[:notice] = "Category was not found"
        redirect_to root_url
      end
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_list_category.html.erb
<% @categories = Category.where("parent_id IS NULL") %>
<h3>List Category</h3>
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category.id), :class => "parent_category" %></li>
    <% @child_categories = Category.where("parent_id = ?", category.id) %>
    <% if !@child_categories.blank? %>
      <ul>
        <% @child_categories.each do |child_category| %>
          <li><%= link_to child_category.name, category_path(child_category.id), :class => "child_category" %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</ul>

app/views/categories/show.html.erb
<div class="content">
  <div class="hr_two"></div>
  <h4>List <%= @category.name %>(s)</h4>
  <div class="hr_two"></div>
  <div class="products">
    <% @products.each do |product| %>
      <div class="product">
        <p>
          Name : <%= product.name %><br />
          Price : <%= product.price %>
          <ul>
            <li><%= link_to "See more", product, :class => "see-more" %></li>
            <% unless session[:user_id].nil? %>
              <% unless current_user.is_admin %>
                <% if current_user.id.eql?(product.user_id) %>
                  <li><%= link_to "Edit", edit_product_path(product), :class => "manage" %></li>
                  <li><%= link_to "Delete", product, :method => :delete, :confirm => "Are You Sure?", :class => "manage" %></li>
                <% end %>
              <% else %>
                <li><%= link_to "Edit", edit_product_path(product), :class => "manage" %></li>
                <li><%= link_to "Delete", product, :method => :delete, :confirm => "Are You Sure?", :class => "manage" %></li>
              <% end %>
            <% end %>
          </ul>
        </p>
      </div>
    <% end %>
  </div>
</div>