config/routes.rb
OnlineStore::Application.routes.draw do
  get "home/index"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :comments
  match 'comment/destroy/:id/:article_id' => 'comments#destroy', :as => :delete_comment

  resources :categories
  resources :sessions
  resources :users
  resources :products
  resources :articles

  root :to => "home#index"
  
  match ':controller(/:action(/:id))(.:format)'

  namespace :admin do
    resources :categories
    match 'category/create' => 'categories#create', :as => :create_category
    match 'category/edit/:id' => 'categories#edit', :as => :edit_category
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online Store</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <header>
    <%= flash[:error] || flash[:notice] %>
    <h1>Welcome to my store</h1>
  </header>
  <nav>
    <ul>
      <li><%= current_user.nil? ? raw(sign_up_link) : raw(home_link) %></li>
      <li><%= link_to "Products", products_path %></li>
      <li><%= link_to "Article", articles_path %></li>
      <% unless session[:user_id].nil? %>
        <% if current_user.is_admin %>
          <li><%= link_to "Category", admin_categories_path %></li>
        <% end %>
      <% end %>
    </ul>
  </nav>
  <div class="clear"></div>
  <aside>
    <% if session[:user_id].nil? %>
      <%= render :partial => "sessions/form" %>
    <% elsif current_user %>
      <%= raw(side_box) %>
    <% end %>
    <% unless session[:user_id].nil? %>
      <% unless controller_name == "categories" %>
        <div class="hr"></div>
        <div class="category_box">
          <%= render :partial => "categories/list_category" %>
        </div>
      <% end %>
      <% if controller_name == "categories" && action_name == "show" %>
        <div class="hr"></div>
        <div class="category_box">
          <%= render :partial => "categories/list_category" %>
        </div>
      <% end %>
    <% end %>
  </aside>
  <section>
    <%= yield %>
  </section>
</div>
</body>
</html>